FROM tensorflow/tensorflow:latest-py3

COPY . .

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y
RUN pip install -r requirements.txt

ENTRYPOINT ["python3", "./server.py"]

EXPOSE 9999