FROM tensorflow/tensorflow:2.5.0-gpu

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y
RUN pip install --upgrade pip

COPY . .
RUN pip install -r requirements.txt
ENTRYPOINT ["python3", "./server.py"]

EXPOSE 9999